### PR TITLE
bench: fix multiple logging with MPI

### PR DESCRIPTION
**Pull request by georgebisbas**
This PR aims to drive MPI bench-logging output to be generated only from one MPI process.

### CODE REVIEW

**Comment by FabioLuporini** [comment]
uncontroversial

**Comment by FabioLuporini** [comment]
is this ready to land? or shall we wait for a ``test_benchmarking`` (not your fault this is missing -- definitely something we should have done ages ago)

**Comment by georgebisbas** [comment]
> is this ready to land? or shall we wait for a `test_benchmarking` (not your fault this is missing -- definitely something we should have done ages ago)

I suggest that as long as tests are missing, we use it temporarily for our purposes from branch and when tests are ready we can land

**Comment by FabioLuporini** [comment]
Im tempted to say that if you tried it, and it seems to do the right thing, I'd fix the remaining flake8 issue and merge it as is. We need to get rid of as many branches as possible at this stage

**Comment by FabioLuporini** [comment]
Merged.

**Pull request merged**
