### PR TITLE
dse: Fix aliases detection

### PR DESCRIPTION
**Pull request by FabioLuporini**
Hopefully uncontroversial

### CODE REVIEW

**Comment by FabioLuporini** [comment]
@mlange05 this fixes the issue we bumped into a few days ago when I asked you to check whether things were working properly in TTI with dse aggressive mode at higher SO order, to eventually find out there was a bug in ``master``, rather than your branch, with SO=16

**Comment by FabioLuporini** [comment]
In fact, I decided this wasn't enough and pushed a DSE test to monitor the operation counts in TTI. This test will probably increase the TRAVIS running time by about 2 mins (only 80secs on my workstation), but I think it's far too important and should really go in. Open to debate, though... let me know what you think @mlange05

**Comment by mlange05** [comment]
Yes, looks alright to me; slightly increased travis times, but still doable it seems

**Comment by FabioLuporini** [comment]
OK, then merging...

**Comment by FabioLuporini** [comment]
Merged.

**Pull request merged**
