### PR TITLE
Pragmas for paralelization and vectorization

### PR DESCRIPTION
**Pull request by felippezacarias**
Generating code with openmp support. The build fails on osx because clang does not support openmp. I tried some workarounds but none of them worked. I also noticed that the code has not been vectorized by the toolchain compiling with gcc, but typing the command  by hand the code is vectorized. Any ideias about it?

### CODE REVIEW

**Comment by navjotk** [comment]
Rebased for a clean diff. Please review.

**Comment by mlange05** [comment]
This branch now needs to be reconciled with master.

**Comment by navjotk** [comment]
Done.

**Comment by mlange05** [comment]
Looks good, merging...

**Pull request merged**
