### PR TITLE
Seismic imaging tutorial

### PR DESCRIPTION
**Pull request by mloubout**
New tutorial on seismic imaging.

Needs some flake8 fix I'll add in a bit.

EDIT July 4th:
- Introduce FWI tutorial. It only contains the python cels for now, the markdown ones are from the imaging tutorial.

### CODE REVIEW

**Comment by FabioLuporini** [comment]
The quality of your commit messages is getting worse rather than improving :) Can you rebase and switch to meaningful messages?

**Comment by FabioLuporini** [comment]
What's the TODO list here?

**Comment by mloubout** [comment]
>What's the TODO list here?

1 - Find time 
2- Improve tect in `rtm`
3- Write text in `fwi`
4- Figure out why TRAVIS keeps complainign about a `str()`
5- Anything I didn't thought of

**Comment by mloubout** [comment]
Took me a while but finally found it. It turns out `pytest` throws an error if a cell of the notebook takes too long to execute which is the case for FWI.

**Comment by mlange05** [comment]
Ok, after a few tweaks and changes I am now happy with the code components of these. I want to go over the textual components once more before merging, but if anyone is interested in reviewing these, feedback and comments would be appreciated. @ggorman @navjotk @philippwitte @mloubout

**Comment by mlange05** [comment]
Ok, I'm fairly happy with these now, so one final round of proof-reading/reviews would be great. Primarily @mloubout, but anyone else is also welcome. @ggorman @navjotk @philippwitte

**Comment by mloubout** [comment]
Looks good to me overall. I'll push some tiny edits later (rtm image should be gray colormap by default and stuff like that)

**Comment by mlange05** [comment]
Excellent. Looking good, so merging...

**Pull request merged**
