### PR TITLE
typos fix

### PR DESCRIPTION
**Pull request by mloubout**
- Removed wrong colorbar naming for `plot_shotrecord` (no label is convention for shot records)

- TimeFucntion name fix in convextion tuto

### CODE REVIEW

**Comment by FabioLuporini** [comment]
OK

**Comment by mloubout** [comment]
@mlange05 any idea on the nbval error?

**Comment by mlange05** [comment]
Yes, you've changed the content of the cell, but not it's recorded output. I think it needs a clean `Kernel -> Restart and Run All`.

**Comment by mlange05** [comment]
Pushed fixes; merging once green.

**Comment by mloubout** [comment]
Sorry, got busy and forgot to getback to it.

**Pull request merged**
