### PR TITLE
examples/seismic: small fix on how space_order is initialized

### PR DESCRIPTION
**Pull request by btrb**

### CODE REVIEW

**Comment by georgebisbas** [comment]
@FabioLuporini here we have a fail in mpi-cell 16
```
examples/mpi/overview.ipynb ................F.                           [100%]
```

**Comment by FabioLuporini** [comment]
@georgebisbas lucky us, at least it's consistent with our previous observations: it happens whenever we change ``configuration``. I have absolutely no idea why that is the case. But as long as it's just this, we can fix it easily; you know what to do?

**Comment by FabioLuporini** [comment]
@btrb thanks for the PR, which is uncontroversial. I'll merge it as soon as the MPI notebook fix is in

**Comment by FabioLuporini** [comment]
Thanks, merged.

**Pull request merged**
