### PR TITLE
Temporary coordinate fix in tti

### PR DESCRIPTION
**Pull request by mloubout**
Temporary coordinate passing to `apply` forgotten in tti

### CODE REVIEW

**Comment by navjotk** [comment]
You won't need to do this after the PR I am about to submit

**Comment by mloubout** [comment]
As I said, temporary fix, don't know when next PR will land and what's in it, just want master to produce correct results.

**Comment by FabioLuporini** [comment]
**if Travis was green without catching this issue, then we have a SERIOUS problem!!!**

**Comment by mloubout** [comment]
Closing as #273 fixes it.

**Pull request closed without merging**
