### PR TITLE
small fixes and improvements

### PR DESCRIPTION
**Pull request by FabioLuporini**
A few minor fixes/improvements, one per commit

### CODE REVIEW

**Comment by mloubout** [comment]
Well while we're at small fixes, `damp,m` allocate wrong size memory in test_adjoint, let me llok into it

**Comment by mloubout** [comment]
On the allocation

I can't reproduce it on my machine, looks like TRAVIS is allocating `m.damp` two times but can't figure out why. This doesn't impact this fixes so can be ignored for now.

**Comment by FabioLuporini** [comment]
> Well while we're at small fixes, damp,m allocate wrong size memory in test_adjoint, let me llok into it

Sorry, where? what example?

**Comment by mloubout** [comment]
>Sorry, where? what example?

All `test_adjointA` in TRAVIS

```
tests/test_adjointA.py::test_acoustic[True-dimensions0-2-4] Allocating memory for m ((70, 70, 70))
Allocating memory for damp ((70, 70, 70))
Allocating memory for src_coords ((1, 3))
Allocating memory for src ((220, 1))
Allocating memory for rec_coords ((50, 3))
Allocating memory for m ((84, 94))
Allocating memory for damp ((84, 94))
Allocating memory for src_coords ((1, 2))
Allocating memory for src ((199, 1))
Allocating memory for rec_coords ((60, 2))
Allocating memory for srca_coords ((1, 2))
Allocating memory for rec_coords ((60, 2))

```

**Comment by mlange05** [comment]
Yes, the allocation has nothing to do with this PR, so still good to go once green.

@mloubout The bug you're reporting is indeed in master and arises due to an accidental naming clash with py.test. Effectively pytest always calls `setup()` before any test invocation, which we accidentally overwrite with `from examples.seismic.acoustic.acoustic_example import setup`. Renaming our function to something like `ac_setup` fixes this and avoids double allocation of `m` and `damp`. That being said, I'm not a big fan of these `setup` methods throughout the test base, since they completely obfuscate our tests to non-devs.

**Comment by mloubout** [comment]
@mlange thanks for finding that out

As of the setup function, it wasn't there originally but I was asked to do it to remove duplicate code in the tests/examples. I don't mind at all removing it.

**Comment by mlange05** [comment]
Yeah, I guess we need to trim the setup code (source, receiver and model initialisation) a bit before we can reasonably pull that out. With the right wrappers that should be no more than like 5-10 lines roughly, at which point the overhead is mall enough to not have to hide things.

**Comment by FabioLuporini** [comment]
Rebased. Travis was already green. I'll merge this as soon as Travis is green again

**Comment by FabioLuporini** [comment]
Merged.

**Pull request merged**
