### PR TITLE
Nbpml to nbl4

### PR DESCRIPTION
**Pull request by btrb**

### CODE REVIEW

**Comment by FabioLuporini** [comment]
@btrb could you take another look? there are pep8 complaints now

**Comment by btrb** [comment]
sure, right away

**Comment by btrb** [comment]
there are two matters from `flake8` that i don't know how to approach from this PR

1) complains are also returned from the `master` branch regarding [these](https://github.com/opesci/devito/blob/master/devito/finite_differences/differentiable.py#L252) methods
```
./devito/finite_differences/differentiable.py:259:5: F811 redefinition of unused '_' from line 255              │ 48         origin = kwargs.pop('origin', tuple([0. for _ in shape]))
./devito/finite_differences/differentiable.py:263:5: F811 redefinition of unused '_' from line 259              │ 49         nbl = kwargs.pop('nbl', 10)
./devito/finite_differences/differentiable.py:267:5: F811 redefinition of unused '_' from line 263              │ 50         dtype = kwargs.pop('dtype', np.float32)
./devito/finite_differences/differentiable.py:271:5: F811 redefinition of unused '_' from line 267 
```

2) there's a conflict between the method `initialize_function` from [PR931](https://github.com/opesci/devito/pull/931) in [devito/buitins.py](https://github.com/opesci/devito/blob/nbpml_to_nbl4/devito/builtins.py#L169)
and the method with same name [model.py](https://github.com/opesci/devito/blob/master/examples/seismic/model.py) 
maybe @rhodrin can give me a hand on how to proceed here

**Comment by FabioLuporini** [comment]
> there's a conflict between the method initialize_function from PR931 in devito/buitins.py
and the method with same in name model.py

you messed up a rebase. In latest master there's no `initialize_function` anymore in model.py. It's been moved under `builtins.py`

> complains are also returned from the master branch regarding these methods

no, this is not an issue. You see them probably because your version of flake8 is different than that used by Travis/pipelines, or because of some local configuration. You can ignore these

You'll have to fix the `initialize_function` mess up, however

**Comment by btrb** [comment]
closed in favor of `nbpml_to_nbl5`

**Comment by FabioLuporini** [comment]
@btrb closed unmerged branches should always be deleted.

**Pull request closed without merging**
