### PR TITLE
replace isinstance(...,int) with is_integer(...)

### PR DESCRIPTION
**Pull request by tjb900**
This tripped me up a lot in the early days.  It's fairly easy to end up with a numpy integer instead of an int, and then unexpected things happen.

### CODE REVIEW

**Comment by tjb900** [comment]
> strictly necessary
Probably not...  I can't actually remember the failing cases, but it made me crazy enough at the time to write the patch :)  I was also not sure, as I submitted this, if it might not be safer to to use `is_integer` for the class-membership tests (so that it behaves the way people expect) but still cast to `int` afterwards so we don't just move the problems elsewhere?

**Comment by FabioLuporini** [comment]
some comments: 
* I can't imagine how can we have something which is not a pure int in function.py
* the fix in operator.py will be dropped as part of #715 , which entirely drops that horrible piece of code
* the fixes in space.py are reasonable . We might enforce int in there, yeah...

**Comment by FabioLuporini** [comment]
(sorry, I accidentally closed the PR for a split second)

**Comment by tjb900** [comment]
Roger, will cut it back to just `space.py` and then can go in after #715

**Comment by FabioLuporini** [comment]
merged.

**Pull request merged**
