### PR TITLE
At update

### PR DESCRIPTION
**Pull request by sheino**
Updating auto tuning logic in response to PR 32.
Refactored and improved some stuff.

### CODE REVIEW

**Comment by navjotk** [comment]
This looks like the next PR in queue. Please rebase your changes on master.

**Comment by sheino** [comment]
@navjotk  Why not just merge? As im strugling with rebasing

**Comment by navjotk** [comment]
Because this PR has 44 commits, some of which have already been included in master. This makes it really hard to review.

**Comment by sheino** [comment]
If I squash lets say DIffusion/Operator commits together to make PR easier to review, aren't there gonna be merge conflicts when merging to master?

**Comment by navjotk** [comment]
I am suggesting a rebase to get rid of all the merge commits in this branch so that it logically moves "on top" of master. This way the only commits here are the ones you made yourself. This also ensures you resolve any conflicts before this happens since right now your branch is conflicting with master anyway - no way this PR can be merged right now. Read [this](https://www.atlassian.com/git/tutorials/merging-vs-rebasing) for a more detailed explanation of why rebase and not merge in this case.

**Comment by sheino** [comment]
Partly corrupted branch. Rebased everything in Auto tuning update branch

**Pull request closed without merging**
