### PR TITLE
Logging infrastructure

### LINKED ISSUE #19: Logging mechanism
We need a logging system to make it easy to find errors.
The same (or a different?) mechanism could be used for profiling and benchmarking.

### PR DESCRIPTION
**Pull request by FabioLuporini**
A basic logging infrastructure 

Example of use in test_diffusion. I think all prints and similar stuff should be moved to this

PERF_OK and PERF_WARN should be used to emit messages concerning performance (times, flop reductions etc)

Fixes #19

### CODE REVIEW

**Comment by mlange05** [comment]
Looks great to me, very neat. We should start introducing some more detailed logging in any future changes to Propagator/Operator/Compiler, etc.

**Comment by vincepandolfo** [comment]
You should add the automodule directive for logger.py to 'docs/devito.rst'

**Comment by FabioLuporini** [comment]
Thanks, done. I think this is now ready

**Comment by navjotk** [comment]
@FabioLuporini The recent merge has created a conflict here. Can you please rebase on master? Once the conflict is resolved and travis is happy, I will merge immediately.

**Comment by FabioLuporini** [comment]
Rebased. Should be OK now. Thanks

**Comment by navjotk** [comment]
Merged.

**Pull request merged**
