### PR TITLE
Adding explicit numpy requirement

### PR DESCRIPTION
**Pull request by mlange05**
Making our version dependency on `numpy` explicit to address issue #96.

### CODE REVIEW

**Comment by FabioLuporini** [comment]
uncontroversial

**Comment by mloubout** [comment]
Shouldn't `pytools`  be in it?
And `numpy` 1.1 needs a separate installation of `mpmath`

**Comment by mlange05** [comment]
`pytools` isn't imported by the core package, but `mpmath` is indeed missing. Good spot, thanks.

**Comment by mloubout** [comment]
>pytools isn't imported by the core package
What do you mean? `cgen` is using `pytools` but only `cgen` in requirements is not installing it

**Comment by mlange05** [comment]
`pip` should take care of any dependencies when it installs `cgen` (the dependency is defined in cgen's `setup.py`). We aren't and shouldn't be responsible for tracking the dependencies of other packages, only our own.

**Comment by mloubout** [comment]
OK

**Comment by navjotk** [comment]
Weird travis failures

**Comment by mlange05** [comment]
Travis-OSX builders sporadically die on our TTI example, probbaly due to the high memory demand crippling the VM. It's all green now though.

**Pull request merged**
