### PR TITLE
Tweak elastic and viscoelastic testing

### PR DESCRIPTION
**Pull request by rhodrin**
Running the 3d elastic example was time consuming and the example was not being 'tested'. This PR removes running (untested) elastic and viscoelastic examples during build testing and now only the 2d simulations with norm tests are run.

### CODE REVIEW

**Comment by mloubout** [comment]
I don't really like that. Yes these are slower but that's not the point. We are running all the other examples I don't see why we should remove these ones or why even bother running any example. The point is we provide examples and we make sure it runs.

**Comment by rhodrin** [comment]
> I don't really like that. Yes these are slower but that's not the point. We are running all the other examples I don't see why we should remove these ones or why even bother running any example. The point is we provide examples and we make sure it runs.

The other examples don't have associated tests. Also, we can't run all elastic and viscoelastic examples examples with all the options a user could provide, so we're not really 'testing' much extra by ensuring that an elastic example doesn't throw a run time error (it could be producing `NaN`'s for 6 minutes).
Maybe we should add a norm test for a small 3d case? But I don't think we should be spending a great deal of time running simulations whose results aren't tested in any sense.

**Comment by rhodrin** [comment]
> Yes these are slower but that's not the point

Also, this point comes back to the discussion we had during the meeting yesterday i.e. Do we want some separate testing suite where longer examples are being run (which I think we should).

**Comment by FabioLuporini** [comment]
Merged.

**Pull request merged**
