### PR TITLE
DSE - code motion and other features

### PR DESCRIPTION
**Pull request by FabioLuporini**
This PR introduces:

* the concept of ``DSE transformation step`` (see the ``dse_transformation`` decorator in symbolics.py)
* a complete new DSE transformation step: code motion. This is implemented in ``_replace_time_invariants``. Time-invariant sub-expressions are sought and given a score. If the score is greater than an empirically determined threshold, then the sub-expression at hand is "lifted" outside the time loop and evaluated in a temporary
* taylor-based approximation of sin/cos. The default choice, however, is still Bhaskara, as tests start failing with Taylor. I wonder if this is due to the remarkably bad approximation that Taylor gives as one gets far from default center, 0
* refactoring and improvements of various nature for the DSE
* extended propagator to emit time-invariant code outside of the time loop
* new tests

I run some tests to verify the impact of the new transformation (single socket, 8 threads, icc O2 xHost, pinning, etc):

* TTI space order 4: runtime drops from 127s to 91s (~1.4X speed-up)
* TTI space order 10: runtime drops from 373s to 322s (1.16X speed-up)

If *no* code motion is performed and sin/cos are replaced with the respective Bhaskara approximations, the execution time in TTI space order 4 only drops from 127s to 105s. 
If code motion is performed and *no* Bhaskara approximation is introduced, than the run-time is pretty much the same (92s in TTI space order 4) *but* the compile time is much higher (icc takes more to vectorize loops with sin/cos). For example, in TTI space order 10, the compilation time drops from 74s to 16s thanks to Bhaskara

### CODE REVIEW

**Comment by mloubout** [comment]
What is 10th order doing there. I already said it multiple timers, for TTI, only runs multiple of 4 orders.

**Comment by FabioLuporini** [comment]
I remembered multiple of 2 . Doesn't really matter in this context though. Any sufficiently high random order suites the purpose here.

**Comment by mloubout** [comment]
Even if it doesn't really matter, the point is we keep running test with this orders that should not be used. So evenso it does not impact your result, it means noone will remember it should not be used if people don't make sure to use it properly wether or not it is for a proper geophysical application. I don't want to ebd up with shotty results in a few month because everyone forgot it again.

**Comment by FabioLuporini** [comment]
Yes, so it's best if we add checks at the beginning of TTI which prevent the execution of what u believe should never be run

**Comment by ggorman** [comment]
I'm supporting @mloubout's point here. It feels like we are leaving behind a landmine for someone to step on...

How about making use of the python warnings module?

**Comment by FabioLuporini** [comment]
I also agree with his point, that's why I proposed to add checks for when one tries to run TTI

**Comment by mloubout** [comment]
Another thing. There is with that PR, no possibilty to disable dse. This is sometimes required for non implemented case (I sended you a private message withone case ). Can we add a `no-dse` case to have everything covered?

**Comment by FabioLuporini** [comment]
@mloubout If you instantiate operators passing ``dse=None``, no DSE transformations is applied

**Comment by mlange05** [comment]
OK, so basically this looks really great - although a little complicated for novices. ;) Tying the allocation of temporaries directly into the Propagator worries me slightly, since it makes the 2.0 re-write harder, but in the interest of time I think we can merge this now and unpick later. Also, the TTI space order discussion is orthogonal to this PR, so I think this is good to go.

**Comment by FabioLuporini** [comment]
Thanks for merging this. The reason temporaries are allocated in the propagator is that the DSE is orthogonal to code generation, as it's just pure expression manipulation. 

I think we have to be prepared in 2.0 to create a general mechanism to allocate temporaries at a certain loop nest depth. With such a mechanism, allocation of temporaries for stencils, additional expressions (eg sparse point interpolation), time invariants etc would be handled uniformly with minimal pain

**Comment by mlange05** [comment]
I agree, I was just pointing out that the "allocation" code used for generic FT on symbols and for temporaries should all come from the same place.

Also, I just realised this, but are we actually freeing temporaries in the kernel too, or are we leaking memory here?

**Comment by FabioLuporini** [comment]
Good spot. I'm 100% I handled that, and in fact now that I look at the code, it's missing other stuff. I must have dropped a commit during an interactive rebase.

I'm rebasing #170 to include what's been shamefully dropped here, so that (amongst the other things missing) we don't leak memory

**Pull request merged**
