### PR TITLE
Revamp autotuning

### PR DESCRIPTION
**Pull request by FabioLuporini**
* 'runtime' mode for 'core' so that we don't waste time
* more tests
* enhanced ``op.apply`` interface (now can pass basic/aggressive/... directly as ``op.apply(autotune=aggressive)`` instead of setting them globally via ``configuration``)

see tests for more info

### CODE REVIEW

**Comment by mloubout** [comment]
So  if I understand that correctly, autontuning is now done on the fly over the first nblock time stpes?

**Comment by FabioLuporini** [comment]
only when setting the runtime mode. The number of time steps spent autotuning depend on several factors (numbers of combinations attempted, ie basic vs aggressive mode, ``options[at-squeezer]``, and other stuff as well)

**Comment by mloubout** [comment]
Ok cool, GTG for me then.

**Comment by FabioLuporini** [comment]
Note: this now depends on #707 , and clearly I want #707 to go in first

**Pull request merged**
