### PR TITLE
adjoint inject/interpolate

### PR DESCRIPTION
**Pull request by mloubout**
I've been told there is not enough test so here is another one.

This one checks that `inject` and `interpolate` are indeed adjoint. It is kind of tested as part of the `adjointA` but I guess it's good to have standalone tests for each functionality.

### CODE REVIEW

**Comment by FabioLuporini** [comment]
Excellent. @mlange05 / @navjotk  merge if happy.

**Comment by navjotk** [comment]
Good to go for me

**Comment by FabioLuporini** [comment]
Merging...

**Comment by FabioLuporini** [comment]
Merged.

**Pull request merged**
