### PR TITLE
Fix logging

### PR DESCRIPTION
**Pull request by navjotk**
Fixes issue #438 
Requires #429

### CODE REVIEW

**Comment by navjotk** [comment]
Should I change the log level back to WARNING - as it is in master?

**Comment by FabioLuporini** [comment]
> Should I change the log level back to WARNING - as it is in master?

wdym? the ``silencio``wrappers for the AT tests should be set to DEBUG

**Comment by FabioLuporini** [comment]
@navjotk Please merge if my answer makes sense

**Comment by navjotk** [comment]
@ggorman had asked to change the log level in travis to WARNING, which is what led us to discover the bug that this PR fixes. #429 [changed](https://github.com/opesci/devito/pull/429/files#diff-354f30a63fb0907d4ad57269548329e3L11) it back to INFO. I'm not sure that was agreed upon.

I'm asking if I should change it back to WARNING in this PR.

**Comment by FabioLuporini** [comment]
On Slack, @ggorman also concluded (replying to @mlange05 ) that "Ok - there is merit in that argument" (motivations to stick to INFO). 
So I'm happy to stick to INFO as I don't have strong opinions for/against it

**Comment by mlange05** [comment]
Despite ongoing travis flakiness, can we merge this one please? This logging bug is breaking my spirit... :frowning:

**Pull request merged**
