### PR TITLE
Fixed bug introduced in #80

### PR DESCRIPTION
**Pull request by vincepandolfo**
Value parameters were added twice to function signature

### CODE REVIEW

**Comment by mlange05** [comment]
Since it changes the MIC code, has this been run and verified with pyMIC?

**Comment by vincepandolfo** [comment]
It does not change it. It is the same code that was already in function_manager.

**Comment by FabioLuporini** [comment]
looks ok

**Comment by mlange05** [comment]
Looks good. Merging...

**Pull request merged**
