### PR TITLE
AT hotfix

### PR DESCRIPTION
**Pull request by FabioLuporini**
@mlange05

### CODE REVIEW

**Comment by navjotk** [comment]
Required: Tests to make sure autotune is a) being called and b) doing its job. This might have been caught by tests like that.

**Comment by FabioLuporini** [comment]
> Required: Tests to make sure autotune is a) being called and b) doing its job. This might have been caught by tests like that.

Good point. Added.

**Comment by FabioLuporini** [comment]
I'd merge it if the latest edits satisfy you, @navjotk , and if Travis is green

**Comment by FabioLuporini** [comment]
OK, I should have fixed a Python3 compatibility issue, will merge once Travis is green.

**Comment by FabioLuporini** [comment]
Merging...

**Comment by FabioLuporini** [comment]
Merged.

**Pull request merged**
