### PR TITLE
Readability

### PR DESCRIPTION
**Pull request by vincepandolfo**
Made some minor changes to improve readability of the code.

- Enforced a 120 characters limit for lines of code
- Added an isort check in travis (https://github.com/timothycrosley/isort) and sorted imports using isort
- Added blank lines to make the code easier to read by dividing it into smaller logical steps

A next step would be rewriting some sections of the code to increase readability since as of right now they are somewhat hard to read. 

Some work needs to be done on the examples as well, I feel they need more comments and detailed explanations to work properly as examples.

### CODE REVIEW

**Comment by FabioLuporini** [comment]
I think this improves readability. GJ

**Comment by mlange05** [comment]
Ok, I find the amount of blank lines inserted in this PR visually straining, but that's a personal opinion. Everything else does indeed improve readability.

**Comment by FabioLuporini** [comment]
I think this should be rebased and merged ASAP

**Comment by navjotk** [comment]
I am alright with merging this PR right away. Objections, @mlange05 ?

**Comment by mlange05** [comment]
Ok, fair enough, go for it.

**Comment by navjotk** [comment]
Merged.

**Pull request merged**
