### PR TITLE
Added slack link to README

### PR DESCRIPTION
**Pull request by navjotk**

### CODE REVIEW

**Comment by mlange05** [comment]
Would this make more sense closer to the top? Who reads READMEs until the end anyway? :wink:

**Comment by FabioLuporini** [comment]
> Would this make more sense closer to the top? Who reads READMEs until the end anyway?

Isn't it almost at the top?

**Comment by navjotk** [comment]
It was changed and rebased in response to the comment

**Comment by mlange05** [comment]
Cool, thanks. GTG

**Pull request merged**
