### PR TITLE
Reorganisation of the intermediate representations

### PR DESCRIPTION
**Pull request by FabioLuporini**
OK, this may look like a punch in the eye to some of you, but (just like other recent PRs) it actually changes nothing in how things work. It's just moving things around, which also has the positive effect of untangling some circular dependencies. 

Commits should be quite self-explanatory. However, in essence, what this PR does is to gather together the various IR representations into a new folder (``ir``). Different IRs are used during different stages of the compilation process. 

Also, a ``symbolics`` folder now contains "all stuff built on top of sympy`` that were previously spread throughout the code base. In particular, some functions/classes/... have been moved from the ``DSE`` to ``symbolics``.

EDIT: why all this? Because in the next PR, I'll need to add proper data dependence analysis, which greatly benefits from having cleanly organised IRs

### CODE REVIEW

**Comment by FabioLuporini** [comment]
Instead of looking at the edits, it's probably more effective taking a look at the new structure of the ``devito`` directory tree

**Comment by mlange05** [comment]
As far as I can tell this all looks good and makes nice sense. Good to go from me.

**Comment by mlange05** [comment]
Argh, this needs a rebase, but is otherwise good to go. @FabioLuporini

**Comment by FabioLuporini** [comment]
Merged.

**Pull request merged**
