### PR TITLE
OpenMP offloading for GPUs

### PR DESCRIPTION
**Pull request by FabioLuporini**
This PR adds GPU offloading support to Devito via Clang.

Instructions to install Clang with offloading support are available [here](https://github.com/opesci/devito/wiki/OpenMP-5-offloading-instructions-%5BFabio%5D)

Now take this example code:
```
from devito import *
grid = Grid(shape=(8, 8))
u = TimeFunction(name='u', grid=grid)
op = Operator(Eq(u.forward, u + 1))
op.apply(time=200000)
print(u.data)
```

and run it with

```
DEVITO_ARCH=clang DEVITO_PLATFORM=nvidiaX python offloading_example_devito.py
```

This is gonna run on your NVidia GPU -- assuming you got one, otherwise it will fail of course.

We are using this toy program as a DLE test. Nothing particularly sophisticated at this stage.

But anyway, the current implementation automatically generates code moving data between host and device as well as offloaded parallel loops.

TODO: Need to add CI/CD. Need to configure Pipelines to use VM's with GPU's with llvm/OpenMP 5 preinstalled.

### CODE REVIEW

**Comment by mloubout** [comment]
>Need to configure Pipelines to use VM's with GPU's with llvm/OpenMP 5 preinstalled.

Probably easy(her) just to make a llvm docker image as a base for GPU pipelines.

**Comment by FabioLuporini** [comment]
To clarify: CI/CD is for a later PR

**Comment by FabioLuporini** [comment]
this is already massive achievement

**Comment by hyviquel** [comment]
this might help to build the docker image: https://llvm.org/docs/Docker.html

**Comment by mloubout** [comment]
I have on built.
'docker run -it --gpus all mloubout/clang-devito:v1.0 /bin/bash`
Has clang/llvm/... installed

**Comment by ggorman** [comment]
> I have on built.
> `docker run -it --gpus all mloubout/clang-devito:v1.0 /bin/bash`
> Has clang/llvm/... installed

Type? Your suggestion results in ```unknown flag: --gpus```

**Comment by mloubout** [comment]
No sorry you need the Nvidia container toolkit for gpu, already had it forgot was required
https://github.com/NVIDIA/nvidia-docker

**Comment by mloubout** [comment]
After thinking about it, I think it's fine to merge it, rebased and will merge once CI done

**Pull request merged**
