### PR TITLE
Re-write JIT compilation infrastructure

### PR DESCRIPTION
**Pull request by mlange05**
This merge aims to address issues #26 and #28 by replacing the current `JitManager` class with a set of `Compiler` objects that encapsulate our "known best" compiler pre-sets, and utilise the `codepy` infrastructure to perform the JIT process. This allows us to take control of compiler flags, and thus tweak them to achieve better performance, and it reduces the number of environment variables used in the code. 

The details of the new JIT compilation infrastructure are:
* `Operator` and `Propagator` now take a `compiler` argument to allow **application** developers to manually control the JIT infrastructure.
* If the `compiler` argument is not explicitly set try to set if from the `DEVITO_ARCH` environment flag, and we default to `GNUCompiler` if this is not set either.
* If the compiler is determined from the environment, we look also for `DEVITO_OPENMP` to determine whether we want threading. We could simplify this even further by inspecting OMP_NUM_THREADS`, but we might want to wait until we have First Touch allocation for this. 
* The current implementation provides four presets:
  * `gnu`/`gcc`: Default GNU compiler; provides a special `GCC ivdep` pragma to the `Propagator`
  * `clang`/`osx`: Clang compiler; this one automatically disables OpenMP and prints a warning
  * `intel`/`icpc`: This one tries to emulate previous settings, but I don't have an Intel setup, so I leave this to others to test and improve.
  * `intel-mic`/`mic`: Special-purpose compiler that is also used to inject the right pieces of `pymic` in the relevant bits of the code. Needs thorough testing and probably fixing, since I wrote this blindly.
* The `Propagator` now also provides two useful properties: `ccode` to get the auto-generated code as a string, without triggering the JIT engine, and `cfunction` which is the `ctypes.FuncPtr` for the created kernel. The `argtypes` for the dynamic kernel invocation have been moved to `FunctionDescriptor`.

Please note that this commit it primarily concerned with the mechanism, not the actual machine-specific flags we use/recommend. These can be assembled by developers with further benchmarking.

Please not also, that one possible extension would be to provide a `CustomCompiler`, which reads standard env variables, like `CC`, `CFLAGS`, `LDFLAGS`, etc. to provide full customisation to adventurous users.

### CODE REVIEW

**Comment by mlange05** [comment]
I also note that various other pieces of work in the pipeline (AT, ivdep, etc.) might be affected by or could benefit from this. So I believe we want to discuss this sooner rather than later. I also plan on updating the README once this has been decided on, to increase the general level of documentation.

**Comment by navjotk** [comment]
First of all, this is great work and will go a long way in improving ease-of-use for the application developer.

My biggest problem with this PR is that:
- Propagator has been the most complicated class of the codebase so far and the source of a lot of confusion in people reading the code.
- To improve readability, it has been my effort for the last month or two, to reduce the size of Propagator
- To this end, I have identified that Propagator serves two purposes right now(before this PR): conversion from symbolic to C and building the loops around it
- It was my intention to separate these two roles into two different classes, since you yourself have been talking about having a class that just manages and represents the loop structures. This would also greatly improve readability by reducing the complexity inside the "Propagator"
- Instead of simplifying, this PR only adds a third orthogonal role of compilation to Propagator. To me, this hurts readability rather than help it.

Going back to the issues that this PR addresses. While this does effectively address the question of finer control over the compilation flags, it still does not address the config file issue. I don't see how this PR eliminates the need for a config file since this just adds to the number of configurable parameter in the library. This number has been rising with every PR since the first time I brought this issue up a month ago and is becoming more of a problem with every subsequent PR.

**Comment by mlange05** [comment]
Ok, first of all, this PR adds `DEVITO_ARCH` but **removes all other environment flags** previously used by the `JitManager`. The exception is `DEVITO_OPENMP` but I would argue that, once we have automatic First Touch, we should just read `OMP_NUM_THREADS`, since we can now explicitly suppress `openmp` for clang. This leaves us with **one Devito-specific variable**, which is simply necessary if you want to support multiple platforms.

Moreover, I would argue that issuer #26 is not just about the number of configurable parameters, but really the "principle of least surprise". By that I mean that we currently require two or three env variables to even get to expected baseline behaviour, which admittedly this is quite bad. With the new way we require none for Linux, and one for Mac and Intel, which I believe is ok, if we document them well. That, however, should not preclude us from adding more env variables *for specific niche features*, ie. adjusting auto-tuner settings or setting special paths for `memmap`. For these however, we should make sure that they are *for experts only* and do not affect normal users who want Devito to "just work". Ideally we would confine these to be defined in `compiler.py` but this is a matter of internal development policy.

**Comment by mlange05** [comment]
Now concerning the complexity of `Propagator` I would argue that, at least to me, its role is to manage the code-generation and kernel execution, while `Operator` deals with the symbolic manipulation into the required format (more to come...). The JIT engine's role is also quite well defined as going from string to executable function, since this part requires no kernel knowledge at all. So I believe the `Propagator`, as the manager of the "backend", should invoke compilation, in the same way it defers the `params` handling and creating `argtypes` to the `FunctionDescriptor`.

Now, for readability I think the additions I made to `Propagator` in this PR are quite concise and well-documented, so I don't feel they affect readability much. On the other hand, I think removing almost 200 lines of `jit_manager.py`, which I always found a bit convoluted to be honest, improves the overall readability of the Devito code quite a bit. However, I also want to make the `Propagator` clearer, and the loop handling I envisioned would probably see the `Propagator` store a list of `Loop` or `IterationSpace` objects that associate symbolic dimension variables like `x`, `y` or `t` with loop bounds, but this requires us to make progress on the "smart symbolics" first. Note though that even in this construct the `Propagator` remains in charge, but delegates specific tasks to the underlying classes.

**Comment by mlange05** [comment]
Please not that I also just pushed an update to the README, which now documents the user-facing env variables and toolchain settings, as well as updating the general description and example pointers.

**Comment by mlange05** [comment]
Ok, rebased on master, awaiting travis results...

**Comment by mlange05** [comment]
@felippezacarias Can you please make sure the `DEVITO_ARCH=intel` and `DEVITO_ARCH=intel-mic` settings compile and run? The current flags for these are just a guess, and I'm not sure I didn't break the `pymic` hooks, so I'd love some reassurance.

**Comment by felippezacarias** [comment]
@mlange05 I tried `DEVITO_ARCH=intel` and it went well. The `DEVITO_ARCH=intel-mic` produced this error: `AttributeError: 'tuple' object has no attribute 'argtypes'`. I was able to find the solution which are small changes on propagator and operator. Should i make the changes and commit or leave it up to you?

**Comment by mlange05** [comment]
@felippezacarias Many thanks for test-driving this. And yes please commit your fixes straight into the branch, so @navjotk and I can have a look.

**Comment by felippezacarias** [comment]
@mlange05 @navjotk Done!

**Comment by mlange05** [comment]
@felippezacarias Very nice. Thanks a lot. Good to go once travis is green.

**Pull request merged**
