### PR TITLE
Redeploying branch 'ops_dev'

### PR DESCRIPTION
**Pull request by btrb**
initial commit; looking for codecov report

### CODE REVIEW

**Comment by FabioLuporini** [comment]
@btrb : not all tests are skipped in the OPS backend. test_resample, test_data, and test_save have at least one test executed.

**Comment by btrb** [comment]
Indeed, there are some tests being executed in `test_resample`, `test_data` and `test_save`. 
Would you like to skip all within those files?

**Comment by FabioLuporini** [comment]
> Would you like to skip all within those files?

yes please!

Let's bring this up to speed and merge it ASAP, otherwise you'll have to keep fixing tests-related conflicts after each new merge into master....

**Comment by FabioLuporini** [comment]
closing in favor of #712 (exactly the same commit history, but it should run the OPS build on Jenkins too)

**Pull request closed without merging**
