### PR TITLE
Add back changes lost in the merge of last PR

### PR DESCRIPTION
**Pull request by navjotk**
I am pulling this out of 386 because it seems to cause test failures and since I haven't written this patch, I wouldn't know what's breaking. Take a look at this patch separately, @FabioLuporini ?

### CODE REVIEW

**Comment by FabioLuporini** [comment]
Yes, sounds good. Low priority ATM though

**Comment by navjotk** [comment]
I would think this change has been incorporated in master in some form or another @FabioLuporini

**Comment by FabioLuporini** [comment]
They still kinda make sense to me, although I haven't had time to look into the issue yet

**Comment by FabioLuporini** [comment]
Low priority, closing

**Pull request closed without merging**
