### PR TITLE
The great API renaming!

### LINKED ISSUE #221: Rename TensorFunction
The name for this class is not very informative nor intuitive about what the class does. Maybe a name like `TensorSymbol` is better.

### PR DESCRIPTION
**Pull request by mlange05**
Requires PR #369.

This merge is largely cosmetic and does not actually change any functionality. It merely renames most of our internal and external data structures to mirror naming conventions used by SymPy and other PDE solving DSLs more closely. For example, we are currently calling symbolic object `xxxData` and data objects `xxxFunction` which is really counter-intuitive - this PR attempts to rectify this. 

It also adds the basic stubs of a "Developer Documentation" page to the website, with a pretty diagram showing the new data structure hierarchy. This is marged as a work-in-progress, as it requires a lot more TLC.

The detailed renaming list:
* `DenseData` -> `Function`
* `TimeData` -> `TimeFunction`
* `ConstantData` -> `Constant`
* `PointData` -> `SparseFunction`
* `CompositeData` -> `CompositeFunction`
* Switched: `SymbolicData` <-> `SymbolicFunction`
*  `ScalarFunction` -> `Scalar`
* `TensorFunction` -> `Array`
* `TensorData` -> `TensorFunction`
* `nodes.Function` -> `nodes.Callable`
* `nodes.FunCall` -> `nodes.Call`

ANd finally, all outward-facing "Function" classes have been moved to a separate submodule in a first step towards untangling `interfaces.py`.

As always, notes comments and opinions are very welcome.

fixes #221

### CODE REVIEW

**Comment by FabioLuporini** [comment]
Yes!! Great. 

A few comments.

I quickly run :
```
git grep TimeData
git grep DenseData
...
```

and it seems we have some leftovers. As discussed offline, we should also apply the changes to all ``yask`` modules and check that everything still works 

I also suggest to rename ``interfaces.py`` into something else. Like ``types.py`` or whatever, but ``interfaces.py`` seems quite misleading at this point

**Comment by mlange05** [comment]
@FabioLuporini Thanks for the suggestion. I've incorporated them all. 

On a sidenote, we still have an orphaned untested example in the acoustic directory that does notseem to be keeping up with latest API changes.

**Comment by FabioLuporini** [comment]
> On a sidenote, we still have an orphaned untested example in the acoustic directory that does notseem to be keeping up with latest API changes.

which one?

I think I'm happy with this to land, I'll rebase #364 if needed

**Comment by mlange05** [comment]
> which one?

`examples/seismic/acoustic/constant_example.py`

**Comment by mlange05** [comment]
Sorry, I meant `examples/seismic/acoustic/gradient_example.py`

**Comment by FabioLuporini** [comment]
can you file an issue for @mloubout ?

**Comment by FabioLuporini** [comment]
How many conflicts for #345 if we land this?

**Comment by mlange05** [comment]
> How many conflicts for #345 if we land this?

Local merges only threw one conflict (surprisingly); actual rebase conflicted on notebooks.

> can you file an issue for @mloubout ?

I believe this is being used as a development scratchpad for checkpointing by @navjotk. I raised concerns about doing this in a public `examples` directory at the time but was overruled... go figure.

**Comment by FabioLuporini** [comment]
> I believe this is being used as a development scratchpad for checkpointing by @navjotk. I raised concerns about doing this in a public examples directory at the time but was overruled... go figure.

I must have missed or forgotten about this. This needs to be fixed

> Local merges only threw one conflict (surprisingly); actual rebase conflicted on notebooks.

good

**Comment by mloubout** [comment]
Looks good to me

For `examples/seismic/acoustic/gradient_example.py`, no idea, @navjotk added it don;t remember what it is supposed to do.

**Comment by FabioLuporini** [comment]
> For examples/seismic/acoustic/gradient_example.py, no idea, @navjotk added it don;t remember what it is supposed to do.

Then we either fix it or we drop it, I guess [/OT]

**Comment by mlange05** [comment]
> Then we either fix it or we drop it, I guess [/OT]

Agreed, although this discussion is completely orthogonal to this PR at this point.

That being said, I vote for drop (as I did before), as it's effectively an unrolled re-implementation of `test_gradient.py` - only that it is much harder to read and comprehend, but sits in our shop window.

**Comment by navjotk** [comment]
Wait until checkpointing is in before taking any call on gradient example. The checkpointing example builds on this example.

**Comment by mlange05** [comment]
@navjotk Sure, this was merely a sidenote and unrelated to this PR. 

I everyone else happy then? I count two oks, so I guess I'm merging this...

**Pull request merged**
