### PR TITLE
IET: Drop `Analysis` cache, to fix memory leak

### PR DESCRIPTION
**Pull request by mlange05**
It's a class-level cache of sympy expressions, that otherwise keeps our functions alive.

### CODE REVIEW

**Comment by mlange05** [comment]
This is still missing a test. I'll add it soon.

**Comment by mlange05** [comment]
Test added. Should be gtg once travis is happy.

**Comment by mloubout** [comment]
Does ir cover the part @philippwitte PR was aiming to fix, which is even if the cache is cleaned, the `Cmemory` isn't.

**Comment by FabioLuporini** [comment]
looks good to me

**Comment by mlange05** [comment]
> Does ir cover the part @philippwitte PR was aiming to fix, which is even if the cache is cleaned, the Cmemory isn't.

It does. The problem was that the cache wasn't really cleared, because there were still legitimate references to `u` dangling around, so the entire `u` was never freed.

**Comment by mlange05** [comment]
Ok, going in....

**Pull request merged**
