### PR TITLE
Support for 3D stencils and higher order in space and time

### PR DESCRIPTION
**Pull request by navjotk**
Generalised the taylor expansion code to make 2D/3D and orders as parameters.

Depends on https://github.com/opesci/devito/pull/15

### CODE REVIEW

**Comment by navjotk** [comment]
I am currently trying to write tests for these additional cases.

**Comment by navjotk** [comment]
Please review.

**Comment by navjotk** [comment]
Please check travis logs. This is not a failing test. All tests pass locally. Travis shows some strange error.

**Comment by mlange05** [comment]
Ok, overall this really looks great, I especially like the parameterized adjoint tests. However, the travis failures seem to be test timeouts and running this locally it looks like `smart_sympy_replace` is the culprit, taking more than 60% of the run-time of an individual test invocation. Is there any way we can optimise these symbolic replacements/substitutions?

**Comment by navjotk** [comment]
Here is a cProfile log: 
````
   ncalls  tottime  percall  cumtime  percall filename:lineno(function)
        1    0.116    0.116   85.673   85.673 benchmark.py:1(<module>)
        1    0.003    0.003   65.274   65.274 AcousticWave2D_codegen.py:71(Forward)
        1    0.002    0.002   62.209   62.209 operators.py:22(apply)
        1   61.245   61.245   61.245   61.245 jit_manager.py:127(wrapped_function)
        2    0.000    0.000   18.858    9.429 linalg.py:1976(norm)
        2   18.858    9.429   18.858    9.429 {numpy.core.multiarray.dot}
        1    0.000    0.000    3.062    3.062 fwi_operators.py:121(__init__)
63945/40436    0.054    0.000    2.202    0.000 cache.py:91(wrapper)
63945/40436    0.195    0.000    2.171    0.000 compatibility.py:878(wrapper)
        1    0.000    0.000    1.564    1.564 fwi_operators.py:11(_init_taylor)
        2    0.002    0.001    1.464    0.732 solvers.py:359(solve)
        2    0.000    0.000    1.389    0.694 solvers.py:1240(_solve)
       32    0.000    0.000    1.260    0.039 simplify.py:384(simplify)
      988    0.017    0.000    1.142    0.001 basic.py:714(subs)
        1    0.000    0.000    0.961    0.961 operators.py:30(get_callable)
        1    0.000    0.000    0.921    0.921 fwi_operators.py:86(smart_sympy_replace)
````

Clearly, the code inside ``init_taylor`` is taking much longer than the sympy replacement. I don't believe there is much to be gained by making the search and replacement faster since the bottleneck is clearly in deriving the stencil from scratch every time. 

My suggestion here would be to reduce the number of higher order test cases (which are also the slower ones) to make this pass on travis.

**Comment by mlange05** [comment]
Did rolling our own symbol replacement function yield any noticeable improvement, or was the pre-processing speed-up simply due to doing each operator pre-processing individually? Other than that, I think this is good to go, so feel free to merge.

**Comment by navjotk** [comment]
I ran cProfile to compare performance. 
``Old`` = wildcard replacement
``New`` = our own search implementation

``Run 1`` = 2D time order = 2, space order = 2
``Run 2`` = 2D time order = 4, space order = 12

The results were obtained by running all 4 operators (Forward, Adjoint, Gradient and Born)
The reported number is the average (over the 4 operators) number of seconds spent inside the ``smart_sympy_replace`` method, as reported by cProfile.

| | Run 1 | Run 2 |
| --- | --- | --- |
| Old | 0.532 | 3.591 |
| New | 0.645 | 5.655 |

Clearly, we are slower after the change.

**Comment by mlange05** [comment]
Ok, thanks for checking that. Can we revert that change then please?

**Comment by mlange05** [comment]
Ok, this looks good to go now, merging...

**Pull request merged**
