### PR TITLE
Versioneer: Adding basic version tracking with versioneer

### PR DESCRIPTION
**Pull request by mlange05**
Adds basic versioning infrastructure to improve pip installs.

### CODE REVIEW

**Comment by FabioLuporini** [comment]
isn't the versioneer pip-installable ?

**Comment by mlange05** [comment]
It is, but it still installs its own script into the package on setup. I think that's for release/deployment workflows, since these need version info, but don't install dependencies.

**Comment by mloubout** [comment]
As this looks like an instal/use PR, can we add a link to opesci.org to the README.

**Comment by mlange05** [comment]
> As this looks like an instal/use PR, can we add a link to opesci.org to the README.

Yes, done.

**Comment by FabioLuporini** [comment]
I wonder whether we should put all these third-party packages in a separate folder.. </picky-mode>

This can land for me

**Pull request merged**
