### PR TITLE
Though that was fixed, guess it disapeared in some master merge

### PR DESCRIPTION
**Pull request by mloubout**
Simple stencil fix for Born. I though it was in one of my previous PR but I guess I messed up somewhere with the merge/rebase.

Anyway, it is a simple typo fix `u->U` in the second stencil and diff operators for Born.

### CODE REVIEW

**Comment by FabioLuporini** [comment]
I'm trusting you and just merging this.

**Comment by FabioLuporini** [comment]
Merged.

**Comment by ggorman** [comment]
Trust?! Is there no test?

**Comment by FabioLuporini** [comment]
No, this is something that has been missing for quite some time. Not sure if they have tests at the Julia level. I don't know how I could write a proper test for Born

**Comment by mloubout** [comment]
There is a test in julia (and the slim branch as the correct Born), but the memory requirements are too high for TRAVIS.

**Comment by FabioLuporini** [comment]
There should be a way of writing a smaller test though. That'd be useful

**Pull request merged**
