### PR TITLE
Force alignment of arrays in memory

### PR DESCRIPTION
**Pull request by navjotk**

### CODE REVIEW

**Comment by mlange05** [comment]
Neat, looks good. Feel free to merge.

**Comment by navjotk** [comment]
Numpy provides a [setflags](http://docs.scipy.org/doc/numpy-1.10.0/reference/generated/numpy.ndarray.setflags.html) method on arrays which has an alignment option. Changing this doesn't actually change anything in the underlying array. It only changes how numpy looks at it.

It also provides a [require](http://docs.scipy.org/doc/numpy-1.10.0/reference/generated/numpy.require.html) method which makes sure an array is aligned. However the size of alignment in this case is internal and quite arbitrary. Reading the discussions (here)[https://github.com/numpy/numpy/issues/5224) it seems like the alignment is to 16 bytes. This seems like it might be aligning for improving SIMD performance. Alignment for optimal cache performance seems like a (huge issue)[https://github.com/numpy/numpy/issues/5312] for numpy and they don't seem to have fixed this yet.

**Comment by navjotk** [comment]
Assuming we need to be able to align to any arbitrary number of bytes, this needs to be implemented ourselves. Implementing this in python is fairly [trivial](http://stackoverflow.com/a/20293172). To implement this in C, we would need to create our own data structures to implement the [buffer protocol](https://docs.python.org/3/c-api/buffer.html) required by numpy, which seems to be a very tedious affair.

**Comment by mlange05** [comment]
I agree, the Python trick you linked might be the quickest and easiest to implement for now, and for our current benchmark purposes we might just want to do this. If we have more complicated data layouts on top of custom alignment I would hope that we might use some [Cython magic](http://docs.cython.org/src/userguide/memoryviews.html#view-cython-arrays) to make this a little less tedious, but that would require adding a small Cython compilation setup. However, if we end up having to go through the buffer protocol and NumPy array API, I would recommend looking at [petsc4py](https://bitbucket.org/petsc/petsc4py), in particular [this code](https://bitbucket.org/petsc/petsc4py/src/27a02b06dbbb2172bfae216963f896d39a232437/src/PETSc/arraynpy.pxi?at=master&fileviewer=file-view-default) for an example.

**Pull request merged**
